### ISSUE TITLE
Updates to data model, incl. permissions and rules

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#2]
## New tables 

- [x] actors: see #18
- [x] memberships: see #19
- [x] actor_measures: see #20
- [x] measure_actors: see #21
- [x] actortypes: see #22
- [x] actortype_taxonomies: see #23
- [x] actor_categories: see #24 
- [x] measuretypes: see #25
- [x] measuretype_taxonomies: see #26
- [x] resources: see #28 
- [x] resourcetypes: see #29
- [x] measure_resources: see #30

#### fields for all tables

* created_at: datetime
* updated_at: datetime
* last_modified_user_id: integer

**Comment by tmfrnz** [comment]
@parndt have pulled this apart into separate issues, one for each table

**Comment by tmfrnz** [comment]
@parndt: please note that users with role "analyst" should not be able to read "draft" content. Sorry I think this was only included in the Navicat file but not in the individual issues (will add now)

**Comment by parndt** [comment]
Thanks, that does help!
